Repository BitGo/BitGoJS, pull requests merged in 2019-07, with the labels that each got.

#403 CT-499: Update package-lock.json entry for bitgo upon version bump
  modules/express/package.json
  modules/express/scripts/update-package-lock.js
Labels: NEEDED FOR NEXT RELEASE, READY FOR REVIEW

#402 CT-558: Run browserify before webpack when producing browser bundle
  modules/core/.npmignore
  modules/core/package.json
  modules/core/webpack.config.js
Labels: NEEDED FOR NEXT RELEASE, READY FOR REVIEW

#381 BG-13088 / Update trade payload to v1.1.1
  modules/core/src/v2/trading/payload.ts
  modules/core/src/v2/trading/tradingAccount.ts
  modules/core/test/v2/fixtures/trading/affirmation.ts
  modules/core/test/v2/fixtures/trading/payload.ts
  modules/core/test/v2/fixtures/trading/settlement.ts
  modules/core/test/v2/unit/trading/affirmation.ts
  modules/core/test/v2/unit/trading/payload.ts
  modules/core/test/v2/unit/trading/settlement.ts
Labels: READY FOR REVIEW

#404 CT-345: Don't use a package-lock.json for core
  modules/core/.npmrc
Labels: READY FOR REVIEW

#405 CT-359: Typescriptify internal.ts
  modules/core/src/v2/internal.ts
Labels: READY FOR REVIEW

#420 CT-365: Typescript webhooks
  modules/core/src/v2/baseCoin.ts
  modules/core/src/v2/webhooks.ts
Labels: READY FOR REVIEW

#421 CT-361: Typescript markets
  modules/core/package.json
  modules/core/src/v2/baseCoin.ts
  modules/core/src/v2/markets.ts
Labels: READY FOR REVIEW

#426 CT-499: Add scripts to help with updating and rebuilding express
  modules/core/test/lib/test_bitgo.ts
  modules/express/package-lock.json
  modules/express/package.json
  modules/express/scripts/update-bitgo.sh
  yarn.lock
Labels: NEEDED FOR NEXT RELEASE, READY FOR REVIEW

#433 CT-358: Improve Typescript support in Enterprise and Enterprises
  modules/core/src/v2/enterprise.ts
  modules/core/src/v2/enterprises.ts
  modules/core/test/v2/unit/enterprise.ts
  modules/core/test/v2/unit/trading/affirmation.ts
  modules/core/test/v2/unit/trading/settlement.ts
Labels: READY FOR REVIEW

#434 CT-383: Fix lint staged, add check to drone, and run prettier
  .drone.jsonnet
  .drone.yml
  modules/core/.lintstagedrc.yml
  modules/core/package.json
  modules/core/src/v2/coinFactory.ts
  modules/core/src/v2/coins/bsv.ts
  modules/core/src/v2/coins/susd.ts
  modules/core/src/v2/coins/tdash.ts
  modules/core/src/v2/coins/tltc.ts
  modules/core/src/v2/environments.ts
  modules/core/src/v2/trading/affirmation.ts
  modules/core/src/v2/trading/affirmations.ts
  modules/core/src/v2/trading/lock.ts
  modules/core/src/v2/trading/settlement.ts
  modules/core/src/v2/trading/settlements.ts
  modules/core/src/v2/trading/trade.ts
  modules/core/src/v2/trading/tradingAccount.ts
  modules/core/src/v2/trading/tradingPartner.ts
  modules/core/test/v2/lib/recovery-nocks.ts
  modules/express/.lintstagedrc.yml
  modules/express/package.json
  package.json
  yarn.lock
Labels: READY FOR REVIEW

#436 CT-383: Fix remaining prettier formatting errors
  modules/core/src/v2/enterprise.ts
  modules/core/src/v2/enterprises.ts
Labels: READY FOR REVIEW

#431 CT-656 - Make explainTransaction methods return promise
  modules/core/example/v2/send-wallet-transaction.js
  modules/core/src/v2/baseCoin.ts
  modules/core/src/v2/coins/abstractUtxoCoin.ts
  modules/core/src/v2/coins/algo.ts
  modules/core/src/v2/coins/eos.ts
  modules/core/src/v2/coins/rmg.ts
  modules/core/src/v2/coins/xlm.ts
  modules/core/src/v2/coins/xrp.ts
  modules/core/test/v2/integration/wallet.ts
  modules/core/test/v2/unit/coins/abstractUtxoCoin.ts
  modules/core/test/v2/unit/coins/btc.ts
  modules/core/test/v2/unit/coins/eos.ts
  modules/core/test/v2/unit/coins/rmg.ts
  modules/core/test/v2/unit/coins/xlm.ts
  modules/core/test/v2/unit/coins/xrp.ts
Labels: DO NOT MERGE, READY FOR REVIEW

#443 CT-362: Typescriptify pendingApproval and pendingApprovals
  .eslintrc.json
  modules/core/src/v2/baseCoin.ts
  modules/core/src/v2/internal.ts
  modules/core/src/v2/keyDeriver.ts
  modules/core/src/v2/pendingApproval.ts
  modules/core/src/v2/pendingApprovals.ts
  modules/core/src/v2/wallet.ts
  modules/core/src/v2/wallets.ts
Labels: READY FOR REVIEW

#449 CT-372: Typescriptify abstractUtxoCoin, part 1
  modules/core/src/errors.ts
  modules/core/src/v2/baseCoin.ts
  modules/core/src/v2/coins/abstractUtxoCoin.ts
  modules/core/src/v2/coins/rmg.ts
  modules/core/src/v2/recovery.ts
Labels: READY FOR REVIEW

#446 CT-369: Typescriptify Util and fix usages
  modules/core/src/bitgo.ts
  modules/core/src/errors.ts
  modules/core/src/keychains.ts
  modules/core/src/util.ts
  modules/core/src/v2/coins/eth.ts
  modules/core/src/v2/coins/token.ts
  modules/core/src/v2/keychains.ts
  modules/core/src/v2/util.ts
  modules/core/src/v2/wallet.ts
  modules/core/src/v2/wallets.ts
  modules/core/test/v2/unit/ethWallet.ts
Labels: READY FOR REVIEW

#450 CT-714: Unify express configuration systems
  Dockerfile
  modules/express/README.md
  modules/express/bin/bitgo-express
  modules/express/package-lock.json
  modules/express/src/args.ts
  modules/express/src/clientRoutes.ts
  modules/express/src/config.ts
  modules/express/src/expressApp.ts
  modules/express/test/unit/bitgoExpress.ts
  modules/express/test/unit/config.ts
Labels: READY FOR REVIEW

#453 CT-709: Further improve BitGo Express README
  modules/express/README.md
Labels: READY FOR REVIEW

#455 CT-774: Copy test_bitgo and testutil subset into express
  modules/core/.npmignore
  modules/core/src/v2/baseCoin.ts
  modules/express/package-lock.json
  modules/express/package.json
  modules/express/test/integration/bitgoExpress.ts
  modules/express/test/integration/bitgoExpressV1.ts
  modules/express/test/integration/eth.ts
  modules/express/test/lib/asserts.ts
  modules/express/test/lib/test_bitgo.ts
  modules/express/test/lib/testutil.ts
  modules/express/test/unit/bitgoExpress.ts
  modules/express/test/unit/config.ts
  modules/express/tsconfig.json
  yarn.lock
Labels: NEEDED FOR NEXT RELEASE
