Repository BitGo/BitGoJS, pull requests merged in 2021-09, with the labels that each got.

#1525 feat(statics): Add 'name' property to networks
  modules/statics/src/networks.ts
Labels: READY FOR REVIEW

#1532 refactor(account-lib): add calculateForwarderV1Address method
  modules/account-lib/package.json
  modules/account-lib/src/coin/eth/utils.ts
  modules/account-lib/test/resources/eth/eth.ts
  modules/account-lib/test/unit/coin/eth/utils.ts
  yarn.lock
Labels: dependencies

#1529 chore(statics): update eos testnet tokens
  modules/statics/src/base.ts
  modules/statics/src/coins.ts
Labels: READY FOR REVIEW

#1488 Stlx 6616 algo features
  modules/account-lib/package.json
  modules/account-lib/src/coin/algo/assetTransferBuilder.ts
  modules/account-lib/src/coin/algo/errors.ts
  modules/account-lib/src/coin/algo/ifaces.ts
  modules/account-lib/src/coin/algo/index.ts
  modules/account-lib/src/coin/algo/keyPair.ts
  modules/account-lib/src/coin/algo/keyRegistrationBuilder.ts
  modules/account-lib/src/coin/algo/seedEncoding.ts
  modules/account-lib/src/coin/algo/transaction.ts
  modules/account-lib/src/coin/algo/transactionBuilder.ts
  modules/account-lib/src/coin/algo/transactionBuilderFactory.ts
  modules/account-lib/src/coin/algo/transferBuilder.ts
  modules/account-lib/src/coin/algo/txnSchema.ts
  modules/account-lib/src/coin/algo/utils.ts
  modules/account-lib/src/coin/baseCoin/ed25519KeyPair.ts
  modules/account-lib/src/utils/crypto.ts
  modules/account-lib/test/resources/algo/index.ts
  modules/account-lib/test/unit/coin/algo/keyPair.ts
  modules/account-lib/test/unit/coin/algo/seedEncoding.ts
  modules/account-lib/test/unit/coin/algo/transaction.ts
  modules/account-lib/test/unit/coin/algo/transactionBuilder/assetTransferBuilder.ts
  modules/account-lib/test/unit/coin/algo/transactionBuilder/base.ts
  modules/account-lib/test/unit/coin/algo/transactionBuilder/keyRegistrationBuilder.ts
  modules/account-lib/test/unit/coin/algo/transactionBuilder/transactionBuilderFactory.ts
  modules/account-lib/test/unit/coin/algo/transactionBuilder/transferBuilder.ts
  modules/account-lib/test/unit/coin/algo/utils.ts
  modules/account-lib/test/unit/coin/hbar/keyPair.ts
  modules/core/package.json
  modules/core/src/config.ts
  modules/core/src/v2/baseCoin.ts
  modules/core/src/v2/coinFactory.ts
  modules/core/src/v2/coins/algo.ts
  modules/core/src/v2/coins/algoToken.ts
  modules/core/src/v2/coins/index.ts
  modules/core/src/v2/internal/seedValidator.ts
  modules/core/src/v2/wallet.ts
  modules/core/test/browser/browser.spec.ts
  modules/core/test/v2/fixtures/coins/algo.ts
  modules/core/test/v2/unit/coins/algo.ts
  modules/core/test/v2/unit/coins/algoToken.ts
  modules/statics/src/index.ts
  yarn.lock
Labels: DO NOT MERGE
