Repository BitGo/BitGoJS, pull requests merged in 2022-07, with the labels that each got.

#2455 Revert "Revert "feat(bitgo): change the names from algo tokens""
  modules/bitgo/example/js/algo/disable-token.js
  modules/bitgo/example/js/algo/enable-token.js
  modules/bitgo/example/ts/algo/disable-token.ts
  modules/bitgo/example/ts/algo/enable-token.ts
  modules/bitgo/test/v2/fixtures/coins/algo.ts
  modules/sdk-coin-algo/src/algo.ts
  modules/sdk-coin-algo/test/unit/algo.ts
  modules/sdk-coin-algo/test/unit/algoToken.ts
  modules/sdk-coin-algo/test/unit/lib/transaction.ts
  modules/statics/src/base.ts
  modules/statics/src/coins.ts
Labels: READY FOR REVIEW

#2500 chore(bitgo): refactor tss utils
  modules/sdk-core/src/bitgo/tss/common.ts
  modules/sdk-core/src/bitgo/tss/eddsa/eddsa.ts
  modules/sdk-core/src/bitgo/tss/index.ts
  modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
  modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
  modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts
  modules/sdk-core/src/bitgo/utils/tss/eddsa/index.ts
  modules/sdk-core/src/bitgo/utils/tss/eddsa/types.ts
  modules/sdk-core/src/bitgo/utils/tss/index.ts
Labels: SKIP_CACHE

#2533 feat(utxo-lib): add full 64 bit support w/ bigints (needed for doge)
  modules/utxo-lib/package.json
  modules/utxo-lib/src/bitgo/Unspent.ts
  modules/utxo-lib/src/bitgo/UtxoTransaction.ts
  modules/utxo-lib/src/bitgo/UtxoTransactionBuilder.ts
  modules/utxo-lib/src/bitgo/dash/DashTransaction.ts
  modules/utxo-lib/src/bitgo/dash/DashTransactionBuilder.ts
  modules/utxo-lib/src/bitgo/index.ts
  modules/utxo-lib/src/bitgo/signature.ts
  modules/utxo-lib/src/bitgo/tnumber.ts
  modules/utxo-lib/src/bitgo/transaction.ts
  modules/utxo-lib/src/bitgo/wallet/Unspent.ts
  modules/utxo-lib/src/bitgo/zcash/ZcashBufferutils.ts
  modules/utxo-lib/src/bitgo/zcash/ZcashTransaction.ts
  modules/utxo-lib/src/bitgo/zcash/ZcashTransactionBuilder.ts
  modules/utxo-lib/src/bitgo/zcash/hashZip0244.ts
  modules/utxo-lib/test/bitgo/nonStandardHalfSigned.ts
  modules/utxo-lib/test/bitgo/signature.ts
  modules/utxo-lib/test/bitgo/signatureModify.ts
  modules/utxo-lib/test/bitgo/tnumber.ts
  modules/utxo-lib/test/bitgo/wallet/WalletUnspent.ts
  modules/utxo-lib/test/bitgo/wallet/util.ts
  modules/utxo-lib/test/bitgo/zcash/hashZip0244.ts
  modules/utxo-lib/test/fixtures_thirdparty/parse.ts
  modules/utxo-lib/test/integration_local_rpc/compare.ts
  modules/utxo-lib/test/integration_local_rpc/fixtures/dogecoinTest/v1/deposit_p2pkh.json
  modules/utxo-lib/test/integration_local_rpc/fixtures/dogecoinTest/v1/deposit_p2sh.json
  modules/utxo-lib/test/integration_local_rpc/fixtures/dogecoinTest/v1/spend_p2sh.json
  modules/utxo-lib/test/integration_local_rpc/generate/RpcClient.ts
  modules/utxo-lib/test/integration_local_rpc/generate/faucet.ts
  modules/utxo-lib/test/integration_local_rpc/generate/main.ts
  modules/utxo-lib/test/integration_local_rpc/generate/outputScripts.util.ts
  modules/utxo-lib/test/integration_local_rpc/parse.ts
  modules/utxo-lib/test/integration_local_rpc/parseDashEvo.ts
  modules/utxo-lib/test/transaction_util.ts
  scripts/sdk-coin-generator/template/boilerplates/utxo/transactionBuilder.ts
  yarn.lock
Labels: BREAKING CHANGE
