Repository BitGo/BitGoJS, pull requests merged in 2024-01, with the labels that each got.

#4173 Win 1421 zksync statics
  modules/sdk-api/src/bitgoAPI.ts
  modules/sdk-api/src/types.ts
  modules/sdk-coin-zketh/package.json
  modules/sdk-coin-zketh/src/lib/resources.ts
  modules/sdk-coin-zketh/src/register.ts
  modules/sdk-coin-zketh/src/zketh.ts
  modules/sdk-coin-zketh/test/fixtures/zketh.ts
  modules/sdk-coin-zketh/test/getBuilder.ts
  modules/sdk-coin-zketh/test/resources.ts
  modules/sdk-coin-zketh/test/unit/transaction.ts
  modules/sdk-coin-zketh/test/unit/zketh.ts
  modules/sdk-coin-zketh/test/unit/zkethToken.ts
Labels: enhancement

#4175 fix(sdk-coin-hbar): hbar transaction valid duration
  modules/sdk-coin-hbar/src/lib/transactionBuilder.ts
  modules/sdk-coin-hbar/test/fixtures/hbar.ts
  modules/sdk-coin-hbar/test/resources/hbar.ts
  modules/sdk-coin-hbar/test/unit/hbar.ts
  modules/sdk-coin-hbar/test/unit/transactionBuilder/tokenTransferBuilder.ts
Labels: bug, enhancement

#4219 fix(sdk-coin-dot): fix dot recovery
  modules/sdk-coin-dot/src/dot.ts
Labels: DO NOT MERGE
